### ISSUE TITLE
AppImageBuilder.script.ExecutionFailed (exited with code 2)

### ISSUE THREAD

**Issue by CineEncoder** [AppImage/AppImageKit#1068]
Hi,
My project: https://github.com/CineEncoder/cine-encoder
When trying to create an Appimage the following error occurs:

```
[helg@Houston Appimage]$ appimage-builder --recipe appimage-builder.yml --skip-test
INFO:script: + rm -rf AppDir  | true
INFO:script: + mkdir -p AppDir/usr/src
INFO:script: + cp main.py  AppDir/usr/src -r
INFO:script: + python3 -m pip install --system --ignore-installed --prefix=/usr --root=AppDir -r ./requirements.txt
WARNING:script: 
WARNING:script: Usage:   
WARNING:script:   /usr/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
WARNING:script:   /usr/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
WARNING:script:   /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...
WARNING:script:   /usr/bin/python3 -m pip install [options] [-e] <local project path> ...
WARNING:script:   /usr/bin/python3 -m pip install [options] <archive url/path> ...
WARNING:script: 
WARNING:script: no such option: --system
Traceback (most recent call last):
  File "/usr/bin/appimage-builder", line 18, in <module>
    __main__();
  File "/usr/lib/python3.8/site-packages/AppImageBuilder/__main__.py", line 59, in __main__
    script.execute()
  File "/usr/lib/python3.8/site-packages/AppImageBuilder/script.py", line 39, in execute
    raise ExecutionFailed("%s exited with code %s" % (instruction, command.return_code))
AppImageBuilder.script.ExecutionFailed: python3 -m pip install --system --ignore-installed --prefix=/usr --root=AppDir -r ./requirements.txt exited with code 2
```
Please tell me what it can be? 
(I need help!!!)

**Comment by probonopd** [comment]
Hi @CineEncoder and welcome to AppImage.

Please ask over at https://github.com/AppImageCrafters/appimage-builder. This project is not about `appimage-builder`.
