### ISSUE TITLE
Cannot mount AppImage, please check your FUSE setup on Debian 11

### ISSUE THREAD

**Issue by fanpero87** [AppImage/AppImageKit#1304]
Hello,
I followed the installation steps provided to install the latest version:
```
user@server:~$ curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
user@server:~$ chmod u+x nvim.appimage
user@server:~$ sudo mv ./nvim.appimage /usr/bin/nvim
user@server:~$ sudo chmod 755 /usr/bin/nvim
```

but I got the following error when trying to run `nvim` on the terminal:
```
ser@server:~$ nvim
fuse: failed to exec fusermount: No such file or directory

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```

Then, I followed the steps on the wiki:
```
user@server:~$ sudo add-apt-repository universe
user@server:~$ sudo apt install libfuse2
```

But since I'm running Debian 11 instead of Ubuntu I got this error:
```
user@server:~$ sudo add-apt-repository universe
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Debian/bullseye

user@server:~$ sudo apt install libfuse2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libfuse2 is already the newest version (2.9.9-5).
libfuse2 set to manually installed.
The following packages were automatically installed and are no longer required:
  apache2-bin bsdmainutils dh-python fdisk gnupg-agent irqbalance libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap libbind9-140 libbind9-161 libbind9-90 libdbus-glib-1-2 libdns-export1104 libdns-export162
  libdns100 libdns1104 libdns1110 libdns162 libevent-2.0-5 libevent-2.1-6 libevent-core-2.1-6
  libevent-pthreads-2.1-6 libfdisk1 libgmime-2.6-0 libhogweed4 libicu57 libirs161 libisc-export1100
  libisc-export160 libisc1100 libisc1105 libisc160 libisc95 libisccc140 libisccc161 libisccc90 libisccfg140
  libisccfg163 libisccfg90 libjasper1 libjson-c3 libltdl7 liblvm2app2.2 liblvm2cmd2.02 liblwres141 liblwres161
  liblwres90 libmcrypt4 libmpfr4 libnftables0 libnotmuch4 libnuma1 libonig4 libpng12-0 libprocps6 libprocps7
  libpth20 libpython3.4-minimal libpython3.4-stdlib libpython3.5-minimal libpython3.5-stdlib libreadline5
  libssl1.0.2 libtalloc2 libunistring0 linux-image-3.16.0-11-amd64 linux-image-3.16.0-5-amd64
  linux-image-4.9.0-19-amd64 php-php-gettext python-cffi python-defusedxml python-ndg-httpsclient python-ply
  python-pyasn1 python-pycparser python-soappy python-wstools python3-asn1crypto python3-mock python3-pbr
  python3-pyasn1 python3.4 python3.4-minimal python3.5 python3.5-minimal sgml-base tcpd xml-core
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 193 not upgraded.
```

Is there a way I can fix this on Debian?

Thanks.

**Comment by probonopd** [comment]
What does `which fusermount` say?

**Comment by marco-websource** [comment]
Try `sudo apt install fuse` for Debian.

**Comment by RokeJulianLockhart** [comment]
@fanpero87, do you have < V3 of `appimagelauncher` installed? I ask because I see this due to [`TheAssassin/AppImageLauncher/issues/711`](https://github.com/TheAssassin/AppImageLauncher/issues/711#issue-2984327169), so that may be your cause.

**Comment by Drsheppard01** [comment]
looks like it's solved https://github.com/TheAssassin/AppImageLauncher/issues/711

**Comment by probonopd** [comment]
If anyone still encounters this, please retry on a "clean" system where AppImageLauncher never had been installed. Thanks!

**Comment by TheAssassin** [comment]
... uninstalling AppImageLauncher and rebooting removes all traces. Just saying.

**Comment by probonopd** [comment]
Ah, maybe it is the _rebooting_ that many people (including myself) missed :-) Thanks!
