### ISSUE TITLE
AppImage containing wxGTK segfaults if wxGTK is also installed on system

### ISSUE THREAD

**Issue by notklaatu** [AppImage/AppImageKit#82]
The AppImage I'm building for my application runs flawlessly on all the computers I've tested it on so far, except when a computer has wxGTK installed on it. It seems that my AppImage attempts to use the sytemwide wx libs instead of its own.

I assume it's just something I'm overlooking in how I prepare the appimage.  It isn't fully automated yet, but so far, this is my Makefile:

```
linux:
    @convert ./usr/share/icons/hicolor/scalable/stopgo.svg -size 256x256 ./usr/share/icons/stopgo.png
    @sh ./genappdir.sh -i ./usr/share/icons/stopgo.png -d ./usr/share/applications/stopgo.desktop $(PKGDIR)
    @cp -rv ./usr $(PKGDIR)
    @mkdir -p $(PKGDIR)/usr/docs/stopgo
    @cp AUTHORS TODO COPYING $(PKGDIR)/usr/docs/stopgo
    @mkdir -p $(PKGDIR)/usr/$(LIB)/python2.7/site-packages/vlc
    @echo "vlc" > $(PKGDIR)/usr/$(LIB)/python2.7/site-packages/vlc.pth
    @unzip thirdparty/python_vlc*egg -d $(PKGDIR)/usr/$(LIB)/python2.7/site-packages/vlc/
    @sh ./rpm2targz.sh thirdparty/wxPython-2.8.12.0-9.el7.$(ARCH).rpm
    @tar xvf wxPython-2.8.12.0-9.el7.$(ARCH).tar.gz -C $(PKGDIR)
    @rm wxPython-2.8.12.0-9.el7.$(ARCH).tar.gz
    @sh ./rpm2targz.sh thirdparty/wxBase-2.8.12-20.el7.$(ARCH).rpm
    @tar xvf wxBase-2.8.12-20.el7.$(ARCH).tar.gz -C $(PKGDIR)
    @sh ./rpm2targz.sh thirdparty/wxGTK-2.8.12-20.el7.$(ARCH).rpm
    @tar xvf wxGTK-2.8.12-20.el7.$(ARCH).tar.gz -C $(PKGDIR)
    @sh ./rpm2targz.sh thirdparty/libpng-1.5.13-5.el7.$(PKGDIR).rpm
    @tar xvf libpng-1.5.13-5.el7.$(PKGDIR).tar.gz ./usr/$(LIB)/libpng15.so.15.13.0 -C $(PKGDIR)/usr/$(LIB)/
    # this part is not automated yet but basically:
    @do stuff for libjpeg-turbo-1.2.90-5.el7.x86_64.rpm
    @do it again for jbigkit-libs-2.0-11.el7.x86_64.rpm
    @again for jbigkit-2.0-11.el7.x86_64.rpm
    @one more time libtiff-4.0.3-14.el7.x86_64.rpm
    @find ./path/to/$(LIB) -type f -exec sed -i -e 's|/usr|././|g' {} \;
    @find ./path/to/$(LIB) -type f -exec sed -i -e 's|././/bin/env|/usr/bin/env|g' {} \;
    @find ./path/to/$(LIB) -type f -exec sed -i -e 's|././/bin/python|/usr/bin/python|g' {} \;
    @$(HOME)/bin/AppImageAssistant.AppDir/package $(PKGDIR) stopgo.AppDir
```

You can take a look at the result with this 64bit build:

http://slackermedia.info/probonopd/stopgo.AppDir

sha256sum 2b72dfa6dde996632e8e107590445c11e6f43dce674e5fad4992b3f547cdfaae

**Comment by probonopd** [comment]
With the following changes I can get your AppImage to work:
```
sudo mount '/home/me/Downloads/stopgo.AppDir' /mnt
cp -r /mnt/ StopGo.AppDir
cd stopgo.AppDir/
wget http://mirror.centos.org/centos/7/os/x86_64/Packages/python-2.7.5-34.el7.x86_64.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/python-libs-2.7.5-34.el7.x86_64.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/SDL-1.2.15-14.el7.x86_64.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/openssl-libs-1.0.1e-42.el7.9.x86_64.rpm
sudo apt-get -y install unp rpm2cpio
unp *rpm
rm -f *rpm
cd ..

# Repack the AppImage with the correct naming scheme
wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppImageAssistant" # (64-bit)
chmod a+x ./AppImageAssistant
APP=StopGo
VERSION=1.0
rm $APP"-"$VERSION"-x86_64.AppImage" || true
./AppImageAssistant ./$APP.AppDir/ $APP"-"$VERSION"-x86_64.AppImage"
```


**However**, the AppImage assumes VLC to be present on the host system. If it is not, I get:

```
me@host:~/stopgo.AppDir$ ./AppRun 
Running from installation...
Running with local libs...
Traceback (most recent call last):
  File "./bin//stopgo", line 57, in <module>
    app.getOptions()
  File "/home/me/stopgo.AppDir/usr/share/pyshared/stopgolibs/app.py", line 41, in getOptions
    gui.main(opts)
  File "/home/me/stopgo.AppDir/usr/share/pyshared/stopgolibs/gui.py", line 724, in main
    window = GUI(None, id=1, title="stopgo", style=wx.DEFAULT_FRAME_STYLE | wx.FULL_REPAINT_ON_RESIZE, clargs=opts)
  File "/home/me/stopgo.AppDir/usr/share/pyshared/stopgolibs/gui.py", line 35, in __init__
    self.InitUI()
  File "/home/me/stopgo.AppDir/usr/share/pyshared/stopgolibs/gui.py", line 110, in InitUI
    self.Instance = vlc.Instance()
  File "/home/me/stopgo.AppDir/usr/lib64/python2.7/site-packages/vlc/vlc.py", line 1551, in __new__
    return libvlc_new(len(args), args)
  File "/home/me/stopgo.AppDir/usr/lib64/python2.7/site-packages/vlc/vlc.py", line 4521, in libvlc_new
    ctypes.c_void_p, ctypes.c_int, ListPOINTER(ctypes.c_char_p))
  File "/home/me/stopgo.AppDir/usr/lib64/python2.7/site-packages/vlc/vlc.py", line 246, in _Cfunction
    raise NameError('no function %r' % (name,))
NameError: no function 'libvlc_new'
```

AppImages should not assume certain software to be installed in the base system. Hence you should consider bundling at least the required parts of VLC as well.

**Comment by probonopd** [comment]
Is this still of concern? AppImageAssistant has been replaced by `appimagetool`. Please try it instead.

**Comment by TheAssassin** [comment]
AppImage type 1 and related tools have been deprecated.
